### ISSUE TITLE
Post upgrade: Missing application files rffNavImage, rffNavOn, rffNavTree

### ISSUE THREAD

**Issue by natechadwick** [percussion/percussioncms#1053]
**Describe the bug**

The Rhythmyx rffNavImage, rffNavom, rffNavTree XML applications are missing from the <InstallDir>/ObjectStore folder after upgrade to 8.1.2 or 8.1.3.  This seems to cause some operations to fail because the content types are installed into the CONTENTTYPES table. 

**To Reproduce**

1. Install 8.1.2
2. Start the instance using <InstallDir>/jetty.StartJetty.bat/sh
3. Note that in the startup log messages for failed to start content type for the rffNav types are listed.
4. Upgrade to 8.1.3, and start,  Note that the same errors occur

**Expected behavior**
* Rhythmyx upgrade
* * If the rffNav application exists, do not overwrite it
* Percussion CM1 upgrade
* * Install the rffNav applications
* PercussionCMS upgrade
* * Install the rffNav applications

**Versions Affected**
* 8.0.3
* 8.1.2
* 8.1.3
  
**Addditional Context**

Related errors from logs:

``
2023-09-05 10:56:13,563 ERROR [Deployer] com.percussion.error.PSDeployException: Application object does not exist: "psx_cerffNavImage"
	at com.percussion.deployer.server.dependencies.PSAppObjectDependencyHandler.getApplication(PSAppObjectDependencyHandler.java:125)
	at com.percussion.deployer.server.dependencies.PSDependencyUtils.getContentTypeTables(PSDependencyUtils.java:496)
	at com.percussion.deployer.server.dependencies.PSDependencyUtils.getAllContentTypeTables(PSDependencyUtils.java:469)
	at com.percussion.deployer.server.dependencies.PSSchemaDependencyHandler.getDependencies(PSSchemaDependencyHandler.java:144)
	at com.percussion.deployer.server.PSDependencyManager.getDependencies(PSDependencyManager.java:840)
	at com.percussion.deployer.server.PSDeploymentHandler.getDeployableElements(PSDeploymentHandler.java:343)
	at com.percussion.deployer.server.PSDeploymentHandler.processRequest(PSDeploymentHandler.java:3496)
	at com.percussion.servlets.PSAppServlet.service(PSAppServlet.java:125)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
``

``
2023-09-05 10:47:46,468 ERROR [Deployer] com.percussion.error.PSDeployException: Application object does not exist: "psx_cerffNavTree"
	at com.percussion.deployer.server.dependencies.PSAppObjectDependencyHandler.getApplication(PSAppObjectDependencyHandler.java:125)
	at com.percussion.deployer.server.dependencies.PSDependencyUtils.getContentTypeTables(PSDependencyUtils.java:496)
	at com.percussion.deployer.server.dependencies.PSDependencyUtils.getAllContentTypeTables(PSDependencyUtils.java:469)
	at com.percussion.deployer.server.dependencies.PSSchemaDependencyHandler.getDependencies(PSSchemaDependencyHandler.java:144)
	at com.percussion.deployer.server.PSDependencyManager.getDependencies(PSDependencyManager.java:838)
	at com.percussion.deployer.server.PSDeploymentHandler.getDeployableElements(PSDeploymentHandler.java:343)
	at com.percussion.deployer.server.PSDeploymentHandler.processRequest(PSDeploymentHandler.java:3496)
	at com.percussion.servlets.PSAppServlet.service(PSAppServlet.java:125)
``
``
14:55:46,578 INFO  [Search] A directory with name 313 exists under lucene indexes folder C:/812cms/jetty/../sys_search/lucene/indexes\ without a known content type.
14:55:46,579 INFO  [Search] A directory with name 314 exists under lucene indexes folder C:/812cms/jetty/../sys_search/lucene/indexes\ without a known content type.
14:55:46,579 INFO  [Search] A directory with name 315 exists under lucene indexes folder C:/812cms/jetty/../sys_search/lucene/indexes\ without a known content type.
``

**Comment by natechadwick** [comment]
Looks like a logic issue in the modules/perc-distribution-tree/src/main/resources/distribution/rxconfig/Installer/install.xml

**Comment by natechadwick** [comment]
Should be resolved by #1056

**Comment by natechadwick** [comment]
Seems like there are still problems with duplicate nav templates after upgrade.

**Comment by natechadwick** [comment]
510-516 RXSLOTTYPES seem to be being added as duplicates. 

This is the workaround.

```
SELECT COUNT(*) FROM PSX_OBJECTRELATIONSHIP WHERE SLOT_ID IN(510,511,513,516);
DELETE FROM RXSLOTTYPE WHERE SLOTID IN(510,511,513,516);
```

These duplicate templates should not be installed. 

-n
