### ISSUE TITLE
After update to 8.1.5 some publishing jobs complete with failures and the sitemap.xml is not generated as expected

### ISSUE THREAD

**Issue by natechadwick** [percussion/percussioncms#1275]
**Describe the bug**

After update to 8.1.5 some publishing jobs complete with failures and the sitemap.xml is not generated as expected.

**To Reproduce**

1. Upgrade to 8.1.5
2. Run a Full Site Publish
3. Job will complete with Failures

```
name=Java/global/percussion/task/perc_SitemapGeneratorTask, while running publishing Job id=26017, Edition 'DCRT_FULL' (323).
java.lang.RuntimeException: javax.jcr.PathNotFoundException: Property rx:page_noindex not found
	at com.percussion.sitemanage.task.impl.PSSiteMapGeneratorTask.perform(PSSiteMapGeneratorTask.java:206) ~[?:?]
	at com.percussion.rx.publisher.impl.PSPublishingJob.runEditionTasks(PSPublishingJob.java:1409) ~[?:?]
	at com.percussion.rx.publisher.impl.PSPublishingJob.runPostTasks(PSPublishingJob.java:1029) ~[?:?]
	at com.percussion.rx.publisher.impl.PSPublishingJob.finishEdition(PSPublishingJob.java:880) ~[?:?]
	at com.percussion.rx.publisher.impl.PSPublishingJob.run(PSPublishingJob.java:813) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_262]
Caused by: javax.jcr.PathNotFoundException: Property rx:page_noindex not found
	at com.percussion.services.contentmgr.data.PSContentNode.getProperty(PSContentNode.java:510) ~[?:?]
	at com.percussion.sitemanage.task.impl.PSSiteMapGeneratorTask.perform(PSSiteMapGeneratorTask.java:196) ~[?:?]
	... 5 more
2024-05-24 09:13:41,246 INFO  [com.percussion.rx.publisher.impl.PSPublishingJob] 
```
**Expected behavior**
Job should run and site map should be generated. 

**Versions Affected**
* 8.1.5

**Comment by natechadwick** [comment]
@ramdev1980  Looks like a regression related to your skip pages with no search indexing fix.

**Comment by rgarg24** [comment]
Hi Nate,
I have tested this and it looks fine.
