### ISSUE TITLE
Rhythmyx upgrade to 8.1.1-SNAPSHOT fails on missing jboss server.xml

### ISSUE THREAD

**Issue by natechadwick** [percussion/percussioncms#419]
**Describe the bug**
If an instance has had the old jboss server at <installdir>/AppServer removed but then ran the VelocitySwitchingTool to change velocity versions, the AppServer directory tree gets recreated with just the Velocity class files deployed to <installdir>\AppServer\server\rx\deploy\rxapp.ear\rxapp.war\WEB-INF\classes\com\percussion\services\assembly\impl\plugin.  This causes the install to fail with:

`
Installer\install.xml:247: java.lang.RuntimeException: java.io.FileNotFoundException: <installdir>\rhythmyx\AppServer\server\rx\deploy\jboss-web.deployer\server.xml (The system cannot find the path specified)
        at com.percussion.utils.container.PSJBossConnectors.load(PSJBossConnectors.java:81)
        at com.percussion.utils.container.adapters.JBossConnectorConfigurationAdapter.load(JBossConnectorConfigurationAdapter.java:48)
        at com.percussion.utils.container.adapters.JBossConnectorConfigurationAdapter.load(JBossConnectorConfigurationAdapter.java:35)
        at com.percussion.utils.container.ConfigurationContextAbstract.lambda$load$0(ConfigurationContextAbstract.java:56)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Sou`

**To Reproduce**
1. On 7.3.2 instance remove the <InstallDir>/AppServer folder.
2. Run the <installDir>/rxconfig/velocity/switchVelocityVersion.bat|sh script to switch versions
3. Confirm the script regenerates the AppServer folder.
4. Try to upgrade to 8.1.1-SNAPSHOT, upgrade will fail

**Expected behavior**
* Upgrade should run through without failure
* VelocitySwitchingTool should not re-create the AppServer folder if it has been removed already.

**Comment by natechadwick** [comment]
This should be resolved.
