### ISSUE TITLE
7.3.2 to 8.1.1. Jetty server startup fails with password encrypt error

### ISSUE THREAD

**Issue by kuldeepmalik** [percussion/percussioncms#462]
D:\Customers\RHYTMarch7\jetty>StartJetty.bat
13:18:34,453 INFO  [log] Logging initialized @1724ms to org.eclipse.jetty.util.log.Slf4jLog
13:18:34,727 INFO  [Server] RxDir set through rxdeploydir system property to D:\Customers\RHYTMarch7\jetty\..
13:18:34,830 WARN  [XmlConfiguration] Config error at <Set name="password">
              <Call class="com.percussion.utils.container.PSStaticContainerUtils" name="decrypt"><Arg>
                  <Property name="perc.ds.6.pwd"/>
                </Arg><Arg>
                  <Property name="perc.ds.6.pwd.encrypted"/>
                </Arg></Call>
            </Set>
13:18:34,831 WARN  [XmlConfiguration] Config error at <New class="org.eclipse.jetty.plus.jndi.Resource" id="perc.ds.6"><Arg/><Arg>java:jdbc/RhythmyxData</Arg><Arg>
     <New class="com.zaxxer.hikari.HikariDataSource"><Arg>
          <New class="com.zaxxer.hikari.HikariConfig"><Set name="poolName">Hikari <Property name="perc.ds.6.name"/> Pool</Set><Set name="connectionTimeout">120000</Set><Set name="minimumIdle">
              <Property default="50" name="perc.ds.6.connections.min"/>
            </Set><Set name="maximumPoolSize">
              <Property default="50" name="perc.ds.6.connections.max"/>
            </Set><Set name="idleTimeout">
              <Property default="600000" name="perc.ds.6.idle.ms"/>
            </Set><Set name="transactionIsolation">TRANSACTION_READ_COMMITTED</Set><Set name="ConnectionTestQuery">
             <Call class="com.percussion.utils.container.PSStaticContainerUtils" name="connectionTestQuery"><Arg>
                  <Property name="perc.ds.6.driver.name"/>
                </Arg><Arg>
                  <Property name="perc.ds.6.connectiontest"/>
                </Arg></Call>
             </Set><Set name="driverClassName">
              <Property name="perc.ds.6.driver.class"/>
            </Set><Set name="jdbcUrl">jdbc:<Property name="perc.ds.6.driver.name"/>:<Property name="perc.ds.6.server"/>
            </Set><Set name="username">
              <Property name="perc.ds.6.uid"/>
            </Set><Set name="password">
              <Call class="com.percussion.utils.container.PSStaticContainerUtils" name="decrypt"><Arg>
                  <Property name="perc.ds.6.pwd"/>
                </Arg><Arg>
                  <Property name="perc.ds.6.pwd.encrypted"/>
                </Arg></Call>
            </Set></New>
       </Arg></New>
  </Arg></New>
13:18:34,831 WARN  [XmlConfiguration]
java.security.PrivilegedActionException: null
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_262]
        at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1857) [jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_262]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_262]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_262]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_262]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.invokeMethod(XmlConfiguration.java:765) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.invokeMethod(XmlConfiguration.java:760) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.call(XmlConfiguration.java:979) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.call(XmlConfiguration.java:942) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.itemValue(XmlConfiguration.java:1536) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.value(XmlConfiguration.java:1441) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.set(XmlConfiguration.java:571) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:509) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.newObj(XmlConfiguration.java:1022) ~[jetty-xml-9.4.43.v202106Exception in thread "main" java.security.PrivilegedActionException: java.lang.reflect.InvocationTargetException
        at java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1857)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.invokeMethod(XmlConfiguration.java:765)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.invokeMethod(XmlConfiguration.java:760)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.call(XmlConfiguration.java:979)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.call(XmlConfiguration.java:942)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.itemValue(XmlConfiguration.java:1536)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.value(XmlConfiguration.java:1441)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.set(XmlConfiguration.java:571)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:509)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.ne29.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.itemValue(XmlConfiguration.java:1540) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.value(XmlConfiguration.java:1441) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.access$700(XmlConfiguration.java:395) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration$Args.<init>(XmlConfiguration.java:1699) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration$Args.<init>(XmlConfiguration.java:1686) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.newObj(XmlConfiguration.java:1011) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.itemVawObj(XmlConfiguration.java:1022)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.itemValue(XmlConfiguration.java:1540)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.value(XmlConfiguration.java:1441)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.access$700(XmlConfiguration.java:395)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration$Args.<init>(XmlConfiguration.java:1699)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration$Args.<init>(XmlConfiguration.java:1686)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.newObj(XmlConfiguration.java:1011)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.itemValue(XmlConfiguration.java:1540)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.value(XmlConfiguration.java:1441)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.access$700(XmlConfiguration.java:395)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguratlue(XmlConfiguration.java:1540) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.value(XmlConfiguration.java:1441) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.access$700(XmlConfiguration.java:395) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration$Args.<init>(XmlConfiguration.java:1699) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration$Args.<init>(XmlConfiguration.java:1686) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.newObj(XmlConfiguration.java:1011) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:521) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:468) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration.configure(XmlConfiguration.java:380) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration.lambda$main$3(XmlConfiguration.java:1893) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        ... 2 more
Caused by: java.lang.IllegalArgumentException: key may not be null or empty
        at com.percussion.legacy.security.deprecated.PSLegacyEncrypter.decrypt(PSLegacyEncrypter.java:309) ~[perc-legacy-8.1.1-SNAPSHOT.jar:?]
        at com.percussion.utils.container.PSStaticContainerUtils.decrypt(PSStaticContainerUtils.java:84) ~[rxutils-8.1.1-SNAPSHOT.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_262]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_262]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpion$Args.<init>(XmlConfiguration.java:1699)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration$Args.<init>(XmlConfiguration.java:1686)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.newObj(XmlConfiguration.java:1011)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:521)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:468)
        at org.eclipse.jetty.xml.XmlConfiguration.configure(XmlConfiguration.java:380)
        at org.eclipse.jetty.xml.XmlConfiguration.lambda$main$3(XmlConfiguration.java:1893)
        ... 2 more
Caused by: java.lang.IllegalArgumentException: key may not be null or empty
        at com.percussion.legacy.security.deprecated.PSLegacyEncrypter.decrypt(PSLegacyEncrypter.java:309)
        at com.percussion.utils.container.PSStaticContainerUtils.decrypt(PSStaticContainerUtils.java:84)
        ... 31 more
l.java:43) ~[?:1.8.0_262]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_262]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.invokeMethod(XmlConfiguration.java:765) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.invokeMethod(XmlConfiguration.java:760) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.call(XmlConfiguration.java:979) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.call(XmlConfiguration.java:942) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.itemValue(XmlConfiguration.java:1536) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.value(XmlConfiguration.java:1441) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.set(XmlConfiguration.java:571) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:509) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.newObj(XmlConfiguration.java:1022) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.itemValue(XmlConfiguration.java:1540) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.value(XmlConfiguration.java:1441) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.access$700(XmlConfiguration.java:395) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration$Args.<init>(XmlConfiguration.java:1699) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration$Args.<init>(XmlConfiguration.java:1686) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.newObj(XmlConfiguration.java:1011) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.itemValue(XmlConfiguration.java:1540) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.value(XmlConfiguration.java:1441) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.access$700(XmlConfiguration.java:395) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration$Args.<init>(XmlConfiguration.java:1699) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration$Args.<init>(XmlConfiguration.java:1686) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.newObj(XmlConfiguration.java:1011) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:521) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:468) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration.configure(XmlConfiguration.java:380) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.xml.XmlConfiguration.lambda$main$3(XmlConfiguration.java:1893) ~[jetty-xml-9.4.43.v20210629.jar:9.4.43.v20210629]
        ... 2 more

**Comment by kuldeepmalik** [comment]
[
[log.txt](https://github.com/percussion/percussioncms/files/8205871/log.txt)
](url)

**Comment by natechadwick** [comment]
This was resolved by https://github.com/percussion/percussioncms/pull/473
