### ISSUE TITLE
CMS Tools: Server Admin- Exception in thread "Thread-4" java.lang.NullPointerException appears on opening the Help. Also Contents tab is showing as blank on Help dialog box

### ISSUE THREAD

**Issue by natechadwick** [percussion/percussioncms#536]
Login Server Admin devtool.

Click on Help button.

Observe the error showing on command prompt.

Parsing failed for http://localhost:9992/Rhythmyx/Docs/Rhythmyx/Server_Administrator/toc.xml

Exception in thread "Thread-4" java.lang.NullPointerException at javax.help.MergeHelpUtilities.mergeNodeChildren(MergeHelpUtilities.java:89) at javax.help.plaf.basic.BasicTOCNavigatorUI.loadData(BasicTOCNavigatorUI.java:218) at javax.help.plaf.basic.BasicTOCNavigatorUI.access$000(BasicTOCNavigatorUI.java:75) at javax.help.plaf.basic.BasicTOCNavigatorUI$NavSwingWorker.construct(BasicTOCNavigatorUI.java:262) at com.sun.java.help.impl.SwingWorker$2.run(SwingWorker.java:139) at java.lang.Thread.run(Unknown Source)

![server-admin](https://user-images.githubusercontent.com/1232206/181262135-0920e694-4888-4bd9-b5c1-977c8577048e.png)

**Comment by natechadwick** [comment]
The toc shows when clicking the index tab so closing this and not seeing any errors so closing this.

**Comment by mariosm1** [comment]
Tested on 8.1 and the help menu does appear with the sidebar and no errors.
