### ISSUE TITLE
Package Installer- Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Algorithm not supported appear while launching Package Installer

### ISSUE THREAD

**Issue by kuldeepmalik** [percussion/percussioncms#538]
Launch Package Installer and observe that following error message gets logged and Package Installer tool does not launch.

D:\Customers\devtool\March3\devtools>PackageInstaller.cmd
Java Version:
java version "1.8.0_321"
Java(TM) SE Runtime Environment (build 1.8.0_321-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.321-b07, mixed mode)
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Algorithm not supported
        at com.percussion.security.PSEncryptionKeyFactory.getKeyGenerator(PSEncryptionKeyFactory.java:65)
        at com.percussion.legacy.security.deprecated.PSCryptographer.decrypt(PSCryptographer.java:236)
        at com.percussion.deployer.client.PSDeploymentServerConnection.decryptPwd(PSDeploymentServerConnection.java:1124)
        at com.percussion.packageinstaller.ui.PSSelectionView$3.actionPerformed(PSSelectionView.java:333)
        at javax.swing.JComboBox.fireActionEvent(Unknown Source)
        at javax.swing.JComboBox.contentsChanged(Unknown Source)
        at javax.swing.AbstractListModel.fireContentsChanged(Unknown Source)
        at javax.swing.DefaultComboBoxModel.setSelectedItem(Unknown Source)
        at javax.swing.DefaultComboBoxModel.addElement(Unknown Source)
        at com.percussion.packageinstaller.ui.PSSelectionView.loadComboBox(PSSelectionView.java:405)
        at com.percussion.packageinstaller.ui.PSSelectionView.init(PSSelectionView.java:98)
        at com.percussion.packageinstaller.ui.PSSelectionView.<init>(PSSelectionView.java:44)
        at com.percussion.packageinstaller.ui.PSPackageInstallerFrame.createMainPanel(PSPackageInstallerFrame.java:99)
        at com.percussion.packageinstaller.ui.PSPackageInstallerFrame.init(PSPackageInstallerFrame.java:73)
        at com.percussion.packageinstaller.ui.PSPackageInstallerFrame.<init>(PSPackageInstallerFrame.java:59)
        at com.percussion.packageinstaller.ui.PSPackageInstallerClient$1.run(PSPackageInstallerClient.java:56)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by natechadwick** [comment]
This issue seems resolved on latest 8.1.3 build.  Marking as resolved.
