### ISSUE TITLE
Package Installer- While installing the package error - "com.percussion.error.PSDeployException: Input document expected by server, none found." appeared

### ISSUE THREAD

**Issue by kuldeepmalik** [percussion/percussioncms#541]
1. Launch Package Installer.
2. Select any package from \<CMSinstall>\Packages\Percussion\
3. Provide server details and click on Install button.
4. Observe the error appeared.
com.percussion.error.PSDeployException: Input document expected by server, none found.
	at com.percussion.deployer.client.PSDeploymentServerConnection.parseServerResponse(PSDeploymentServerConnection.java:1318)
	at com.percussion.deployer.client.PSDeploymentServerConnection.execute(PSDeploymentServerConnection.java:596)
	at com.percussion.deployer.client.PSDeploymentServerConnection.execute(PSDeploymentServerConnection.java:472)
	at com.percussion.deployer.client.PSDeploymentServerConnection.execute(PSDeploymentServerConnection.java:423)
	at com.percussion.deployer.client.PSDeploymentServerConnection.connect(PSDeploymentServerConnection.java:1166)
	at com.percussion.deployer.client.PSDeploymentServerConnection.<init>(PSDeploymentServerConnection.java:205)
	at com.percussion.packager.ui.managers.PSServerConnectionManager.initConnection(PSServerConnectionManager.java:281)
	at com.percussion.packager.ui.managers.PSServerConnectionManager.initConnection(PSServerConnectionManager.java:227)
	at com.percussion.packageinstaller.ui.PSPackageInstallerFrame.doInstall(PSPackageInstallerFrame.java:410)
	at com.percussion.packageinstaller.ui.PSPackageInstallerFrame.actionPerformed(PSPackageInstallerFrame.java:382)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at org.jvnet.substance.utils.RolloverButtonListener.mouseReleased(RolloverButtonListener.java:111)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by natechadwick-intsof** [comment]
Issue migrated to: https://github.com/intersoftdatalabs-in/percussioncms/issues/955

**Comment by natechadwick-intsof** [comment]
Issue closed and migrated to: https://github.com/intersoftdatalabs-in/percussioncms/issues/955
