### ISSUE TITLE
While login Package Builder error "Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Algorithm not supported" appeared.

### ISSUE THREAD

**Issue by kuldeepmalik** [percussion/percussioncms#543]
1. Run CMS 8.1.1 server.
2. Launch Content Explorer, provide details to connect CM 8.1.1 server and click on ‘Save & Connect’ button.
3. Observe the error.
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Algorithm not supported
        at com.percussion.security.PSEncryptionKeyFactory.getKeyGenerator(PSEncryptionKeyFactory.java:65)
        at com.percussion.legacy.security.deprecated.PSCryptographer.decrypt(PSCryptographer.java:236)
        at com.percussion.deployer.client.PSDeploymentServerConnection.decryptPwd(PSDeploymentServerConnection.java:1126)
        at com.percussion.packager.ui.PSServerManagerDialog.loadFields(PSServerManagerDialog.java:490)
        at com.percussion.packager.ui.PSServerManagerDialog.valueChanged(PSServerManagerDialog.java:253)
        at javax.swing.JList.fireSelectionValueChanged(Unknown Source)
        at javax.swing.JList$ListSelectionHandler.valueChanged(Unknown Source)
        at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
        at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
        at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
        at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
        at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
        at javax.swing.DefaultListSelectionModel.setSelectionInterval(Unknown Source)
        at javax.swing.JList.setSelectedIndex(Unknown Source)
        at com.percussion.packager.ui.PSServerManagerDialog.selectServer(PSServerManagerDialog.java:433)
        at com.percussion.packager.ui.PSServerManagerDialog.onSave(PSServerManagerDialog.java:339)
        at com.percussion.packager.ui.PSServerManagerDialog.actionPerformed(PSServerManagerDialog.java:231)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
        at org.jvnet.substance.utils.RolloverButtonListener.mouseReleased(RolloverButtonListener.java:111)
        at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.WaitDispatchSupport$2.run(Unknown Source)
        at java.awt.WaitDispatchSupport$4.run(Unknown Source)
        at java.awt.WaitDispatchSupport$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.awt.WaitDispatchSupport.enter(Unknown Source)
        at java.awt.Dialog.show(Unknown Source)
        at java.awt.Component.show(Unknown Source)
        at java.awt.Component.setVisible(Unknown Source)
        at java.awt.Window.setVisible(Unknown Source)
        at java.awt.Dialog.setVisible(Unknown Source)
        at com.percussion.guitools.PSDialog.setVisible(PSDialog.java:408)
        at com.percussion.packager.ui.PSServerManagerDialog.setVisible(PSServerManagerDialog.java:285)
        at com.percussion.packager.ui.PSPackagerMainFrame.onOpenServerManager(PSPackagerMainFrame.java:1168)
        at com.percussion.packager.ui.PSPackagerMainFrame.initialServerConnect(PSPackagerMainFrame.java:381)
        at com.percussion.packager.ui.PSPackagerClient$1.run(PSPackagerClient.java:57)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by natechadwick-intsof** [comment]
Issue migrated to: https://github.com/intersoftdatalabs-in/percussioncms/issues/956

**Comment by natechadwick-intsof** [comment]
Issue closed and migrated to: https://github.com/intersoftdatalabs-in/percussioncms/issues/956
