### ISSUE TITLE
Server Admin- Exception in thread "Thread-4" java.lang.NullPointerException appears on opening the Help. Also Contents tab is showing as blank on Help dialog box

### ISSUE THREAD

**Issue by kuldeepmalik** [percussion/percussioncms#552]
1. Login Server Admin devtool.
2. Click on Help button.
3. Observe the error showing on command prompt.

Parsing failed for http://localhost:9992/Rhythmyx/Docs/Rhythmyx/Server_Administrator/toc.xml
<div class='perc-login row center-block'>
Exception in thread "Thread-4" java.lang.NullPointerException
        at javax.help.MergeHelpUtilities.mergeNodeChildren(MergeHelpUtilities.java:89)
        at javax.help.plaf.basic.BasicTOCNavigatorUI.loadData(BasicTOCNavigatorUI.java:218)
        at javax.help.plaf.basic.BasicTOCNavigatorUI.access$000(BasicTOCNavigatorUI.java:75)
        at javax.help.plaf.basic.BasicTOCNavigatorUI$NavSwingWorker.construct(BasicTOCNavigatorUI.java:262)
        at com.sun.java.help.impl.SwingWorker$2.run(SwingWorker.java:139)
        at java.lang.Thread.run(Unknown Source)

![image](https://user-images.githubusercontent.com/77011198/157651092-90049c58-803b-4a85-9bc9-102666984370.png)

**Comment by natechadwick** [comment]
Should be resolved.
