### ISSUE TITLE
Error appears while connecting Content Explorer tool with Rhythmyx 7.3.2- java.io.IOException: java.io.IOException: com.percussion.error.PSException: null

### ISSUE THREAD

**Issue by kuldeepmalik** [percussion/percussioncms#556]
Step 1. Bring up Rhythmyx 7.3.2. server.
Step 2. Launch Content explorer application and try connecting with Rhythmyx server.
Step 3. Observe that Content Explorer login dialog gets close and error logged on console

![image](https://user-images.githubusercontent.com/77011198/156581740-886f54a4-b8d8-45f3-a8b5-99abffa756c7.png)
![image](https://user-images.githubusercontent.com/77011198/156581725-2fcc8ceb-153a-41bf-9f68-4bb0334e44a7.png)

SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
19:43:24.241 [SwingWorker-pool-5-thread-1] INFO  com.percussion.cx.PSCESessionManager - logged in using community Enterprise_Investments locale = en-us
19:43:24.241 [SwingWorker-pool-5-thread-1] INFO  com.percussion.cx.PSCESessionManager - session=c020a87d7834fe151198fa1d26b484b1563b76e8
19:43:24.305 [AWT-EventQueue-0] INFO  com.percussion.cx.PSAjaxSwingWrapperLocator - Running Applet in Browser context
19:43:25.016 [AWT-EventQueue-0] ERROR com.percussion.util.PSRemoteAppletRequester - RemoteAppletRequester error null C:com.percussion.util.PSHttpConnection:L:421
java.io.IOException: java.io.IOException: com.percussion.error.PSException: null
        at com.percussion.cx.PSContentExplorerApplet.getXMLDocument(PSContentExplorerApplet.java:2045)
        at com.percussion.cx.PSContentExplorerApplet.getXMLDocument(PSContentExplorerApplet.java:1987)
        at com.percussion.cx.PSContentExplorerApplet.getParameterDocument(PSContentExplorerApplet.java:1789)
        at com.percussion.cx.PSContentExplorerApplet.initView(PSContentExplorerApplet.java:1138)
        at com.percussion.cx.PSContentExplorerApplet.setupApplet(PSContentExplorerApplet.java:344)
        at com.percussion.cx.PSContentExplorerApplet.init(PSContentExplorerApplet.java:154)
        at com.percussion.cx.PSContentExplorerFrame.initCESession(PSContentExplorerFrame.java:265)
        at com.percussion.cx.PSContentExplorerLoginPanel$2.done(PSContentExplorerLoginPanel.java:573)
        at javax.swing.SwingWorker$5.run(Unknown Source)
        at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
        at sun.swing.AccumulativeRunnable.run(Unknown Source)
        at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
        at javax.swing.Timer.fireActionPerformed(Unknown Source)
        at javax.swing.Timer$DoPostEvent.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
java.io.IOException: java.io.IOException: com.percussion.error.PSException: null
        at com.percussion.cx.PSContentExplorerApplet.getXMLDocument(PSContentExplorerApplet.java:2045)
        at com.percussion.cx.PSContentExplorerApplet.getXMLDocument(PSContentExplorerApplet.java:1987)
        at com.percussion.cx.PSContentExplorerApplet.getParameterDocument(PSContentExplorerApplet.java:1789)
        at com.percussion.cx.PSContentExplorerApplet.initView(PSContentExplorerApplet.java:1138)
        at com.percussion.cx.PSContentExplorerApplet.setupApplet(PSContentExplorerApplet.java:344)
        at com.percussion.cx.PSContentExplorerApplet.init(PSContentExplorerApplet.java:154)
        at com.percussion.cx.PSContentExplorerFrame.initCESession(PSContentExplorerFrame.java:265)
        at com.percussion.cx.PSContentExplorerLoginPanel$2.done(PSContentExplorerLoginPanel.java:573)
        at javax.swing.SwingWorker$5.run(Unknown Source)
        at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
        at sun.swing.AccumulativeRunnable.run(Unknown Source)
        at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
        at javax.swing.Timer.fireActionPerformed(Unknown Source)
        at javax.swing.Timer$DoPostEvent.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by kuldeepmalik** [comment]
Installed Rhythmyx 7.3.2, applied patch and now I am able to connect Content Explorer application therefore closing this ticket.
