### ISSUE TITLE
Getting Velocity Error after upgrading Rhythmyx instance  (with custom vm files) to 8.1.1 on server startup

### ISSUE THREAD

**Issue by sonyDeswal** [percussion/percussioncms#702]
**Describe the bug**
Getting Velocity Error after upgrading Rhythmyx instance  (with custom vm files) to 8.1.1 on server startup

**To Reproduce**
1. Have a Rhythmyx Instance with some custom vm file in rx_resources/vm dir.
2. Upgrade the instance to 8.1.1
3. Startup Jetty Server and  you will see error:-
23:18:15,501 INFO  [PSVelocityAssembler] Velocity properties initialized from /home/support/Customers2/Rhythmyx/rxconfig/Server/velocity.properties
23:18:16,284 ERROR [loader] ResourceManager: parse exception: Lexical error,   Encountered: "\u200b" (8203), after : "" at programme.vm[line 208, column 23]
23:18:16,285 ERROR [macro] Velocimacro: Error using VM library: programme.vm
org.apache.velocity.exception.ParseErrorException: Lexical error,   Encountered: "\u200b" (8203), after : "" at programme.vm[line 208, column 23]
        at org.apache.velocity.Template.process(Template.java:154) ~[velocity-engine-core-2.3.jar:2.3]
        at org.apache.velocity.runtime.resource.ResourceManagerImpl.loadResource(ResourceManagerImpl.java:429) ~[velocity-engine-core-2.3.jar:2.3]
        at org.apache.velocity.runtime.resource.ResourceManagerImpl.getResource(ResourceManagerImpl.java:346) ~[velocity-engine-core-2.3.jar:2.3]
        at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:1677) ~[velocity-engine-core-2.3.jar:2.3]
        at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:1656) ~[velocity-engine-core-2.3.jar:2.3]
        at org.apache.velocity.runtime.VelocimacroFactory.initVelocimacro(VelocimacroFactory.java:205) ~[velocity-engine-core-2.3.jar:2.3]

**Expected behavior**
There should not be any error on startup

**Comment by sonyDeswal** [comment]
This appears to be in customer source file.
